const modelsByBrand = {
  "Acura": [
    "CL",
    "CSX",
    "EL",
    "ILX",
    "Integra",
    "Legend",
    "MDX",
    "NSX",
    "RDX",
    "RL",
    "RLX",
    "RSX",
    "SLX",
    "TL",
    "TLX",
    "TSX",
    "ZDX"
  ],
  "Alfa Romeo": [
    "4C",
    "8C",
    "33",
    "75",
    "90",
    "145",
    "146",
    "147",
    "155",
    "156",
    "159",
    "164",
    "166",
    "Alfasud",
    "Alfetta",
    "Brera",
    "Giulia",
    "Giulietta",
    "GTV",
    "MiTo",
    "Spider",
    "Stelvio",
    "Tonale"
  ],
  "Aston Martin": [
    "AR1",
    "Cygnet",
    "DB7",
    "DB9",
    "DB10",
    "DB11",
    "DB12",
    "DBS",
    "DBX",
    "Lagonda",
    "One-77",
    "Rapide",
    "V12 Vantage",
    "V8 Vantage",
    "Valkyrie",
    "Valour",
    "Vanquish",
    "Virage",
    "Zagato"
  ],
  "Audi": [
    "50",
    "80",
    "90",
    "100",
    "200",
    "A1",
    "A2",
    "A3",
    "A4",
    "A5",
    "A6",
    "A7",
    "A8",
    "Allroad",
    "Cabriolet",
    "Coupe",
    "e-tron",
    "e-tron GT",
    "Q2",
    "Q3",
    "Q4 e-tron",
    "Q5",
    "Q5 e-tron",
    "Q6",
    "Q7",
    "Q8",
    "Q8 e-tron",
    "R8",
    "RS2",
    "RS3",
    "RS4",
    "RS5",
    "RS6",
    "RS7",
    "RS Q3",
    "RS Q8",
    "S1",
    "S2",
    "S3",
    "S4",
    "S5",
    "S6",
    "S7",
    "S8",
    "SQ2",
    "SQ5",
    "SQ7",
    "SQ8",
    "TT",
    "TTS",
    "TT RS",
    "V8"
  ],
  "Aurus": [
    "Komendant",
    "Senat"
  ],
  "BAIC": [
    "BJ20",
    "BJ40",
    "BJ80",
    "EU5",
    "EU7",
    "U5",
    "U5 Plus",
    "X3",
    "X5",
    "X7",
    "X35",
    "X55",
    "X65"
  ],
  "Bentley": [
    "Arnage",
    "Azure",
    "Bentayga",
    "Brooklands",
    "Continental",
    "Continental GT",
    "Eight",
    "Flying Spur",
    "Mulsanne",
    "Turbo R",
    "Turbo RT",
    "Turbo S"
  ],
  "BMW": [
    "1 series",
    "2 series",
    "3 series",
    "4 series",
    "5 series",
    "6 series",
    "7 series",
    "8 series",
    "i3",
    "i4",
    "i5",
    "i7",
    "i8",
    "iX",
    "iX1",
    "iX2",
    "iX3",
    "X1",
    "X2",
    "X3",
    "X4",
    "X5",
    "X6",
    "X7",
    "XM",
    "Z1",
    "Z3",
    "Z4",
    "Z8",
    "M2",
    "M3",
    "M4",
    "M5",
    "M6",
    "M8",
    "X3 M",
    "X4 M",
    "X5 M",
    "X6 M",
    "02 (E10)",
    "2002",
    "501",
    "502",
    "503",
    "507",
    "600",
    "700",
    "E3",
    "E9"
  ],
  "Brilliance": [
    "BC3",
    "BS2",
    "BS4",
    "BS6",
    "FRV",
    "H230",
    "H320",
    "H330",
    "H530",
    "M1",
    "M2",
    "M3",
    "V3",
    "V5",
    "V6",
    "V7"
  ],
  "Buick": [
    "Cascada",
    "Century",
    "Electra",
    "Enclave",
    "Encore",
    "Encore GX",
    "Envision",
    "GL8",
    "LaCrosse",
    "LeSabre",
    "Lucerne",
    "Park Avenue",
    "Rainier",
    "Regal",
    "Rendezvous",
    "Riviera",
    "Roadmaster",
    "Skyhawk",
    "Skylark",
    "Somerset",
    "Terraza",
    "Verano"
  ],
  "BYD": [
    "Atto 3",
    "Dolphin",
    "e2",
    "e3",
    "e6",
    "F0",
    "F3",
    "G3",
    "G5",
    "G6",
    "Han",
    "L3",
    "M6",
    "S6",
    "S7",
    "Seal",
    "Song",
    "Song L",
    "Song Plus",
    "Song Pro",
    "Tang",
    "Yuan",
    "Yuan Plus"
  ],
  "Cadillac": [
    "ATS",
    "ATS-V",
    "BLS",
    "CT4",
    "CT5",
    "CT6",
    "CTS",
    "CTS-V",
    "DeVille",
    "DTS",
    "Eldorado",
    "Escalade",
    "Escalade ESV",
    "Fleetwood",
    "Lyriq",
    "Seville",
    "SRX",
    "STS",
    "XLR",
    "XT4",
    "XT5",
    "XT6",
    "XTS"
  ],
  "Changan": [
    "Alsvin",
    "Benni",
    "CS15",
    "CS35",
    "CS35 Plus",
    "CS55",
    "CS55 Plus",
    "CS75",
    "CS75 Plus",
    "CS85",
    "CS95",
    "Eado",
    "Eado DT",
    "Eado Plus",
    "Hunter",
    "Raeton",
    "Raeton CC",
    "UNI-K",
    "UNI-T",
    "UNI-V",
    "Z-Shine"
  ],
  "Chery": [
    "Amulet",
    "Arrizo 3",
    "Arrizo 5",
    "Arrizo 6",
    "Arrizo 7",
    "Arrizo 8",
    "Arrizo GX",
    "Arrizo M7",
    "Bonus",
    "CrossEastar",
    "E3",
    "E5",
    "Fora",
    "IndiS",
    "Jaggi",
    "Kimo",
    "M11",
    "Omoda 5",
    "QQ",
    "QQ6",
    "Sweet",
    "Tiggo 2",
    "Tiggo 3",
    "Tiggo 3x",
    "Tiggo 4",
    "Tiggo 5",
    "Tiggo 5x",
    "Tiggo 7",
    "Tiggo 7 Pro",
    "Tiggo 8",
    "Tiggo 8 Pro",
    "Tiggo 8 Pro Max",
    "Tiggo 9",
    "Very"
  ],
  "Chevrolet": [
    "3100",
    "Agile",
    "Astro",
    "Avalanche",
    "Aveo",
    "Beat",
    "Bel Air",
    "Beretta",
    "Blazer",
    "Bolt",
    "Bolt EUV",
    "Camaro",
    "Caprice",
    "Captiva",
    "Cavalier",
    "Celebrity",
    "Celta",
    "Chevelle",
    "Chevy",
    "Citation",
    "Classic",
    "Cobalt",
    "Colorado",
    "Corsa",
    "Corsica",
    "Corvette",
    "Cruze",
    "D-20",
    "Epica",
    "Equinox",
    "Evanda",
    "Express",
    "Groove",
    "HHR",
    "Impala",
    "Kalos",
    "Lacetti",
    "Lacheti",
    "Lanos",
    "LUV",
    "Malibu",
    "Matiz",
    "Menlo",
    "Meriva",
    "Metro",
    "Montana",
    "Monte Carlo",
    "Niva",
    "Nova",
    "Onix",
    "Optra",
    "Orlando",
    "Prizm",
    "Rezzo",
    "S-10",
    "Sail",
    "Silverado",
    "Sonic",
    "Spark",
    "Spark GT",
    "Spectrum",
    "Sprint",
    "SSR",
    "Suburban",
    "Tahoe",
    "Tavera",
    "Tornado",
    "Tracker",
    "TrailBlazer",
    "Traverse",
    "Trax",
    "Uplander",
    "Vectra",
    "Venture",
    "Volt",
    "Zafira"
  ],
  "Chrysler": [
    "200",
    "300",
    "300C",
    "300M",
    "Aspen",
    "Cirrus",
    "Concorde",
    "Conquest",
    "Cordoba",
    "Crossfire",
    "Daytona",
    "Dynasty",
    "Fifth Avenue",
    "Grand Voyager",
    "Imperial",
    "LHS",
    "LeBaron",
    "Neon",
    "New Yorker",
    "Newport",
    "Pacifica",
    "Prowler",
    "PT Cruiser",
    "Saratoga",
    "Sebring",
    "Stratos",
    "Town & Country",
    "Valiant",
    "Viper",
    "Vision",
    "Voyager"
  ],
  "Citroën": [
    "2CV",
    "Axel",
    "Berlingo",
    "C-Crosser",
    "C-Elysée",
    "C-Zero",
    "C1",
    "C2",
    "C3",
    "C3 Aircross",
    "C3 Picasso",
    "C4",
    "C4 Cactus",
    "C4 Picasso",
    "C4 SpaceTourer",
    "C5",
    "C5 Aircross",
    "C5 X",
    "C6",
    "C8",
    "DS",
    "DS3",
    "DS4",
    "DS5",
    "E-Méhari",
    "Evasion",
    "Grand C4 Picasso",
    "GS",
    "GSA",
    "Jumper",
    "Jumpy",
    "LN",
    "LNA",
    "Méhari",
    "Nemo",
    "Rosalie",
    "Saxo",
    "SM",
    "SpaceTourer",
    "Traction Avant",
    "Visa",
    "Xantia",
    "XM",
    "Xsara",
    "Xsara Picasso",
    "ZX"
  ],
  "Cupra": [
    "Ateca",
    "Born",
    "Formentor",
    "Leon",
    "Tavascan"
  ],
  "Dacia": [
    "1310",
    "Duster",
    "Jogger",
    "Logan",
    "Logan MCV",
    "Nova",
    "Sandero",
    "Sandero Stepway",
    "Solenza",
    "Spring",
    "SuperNova"
  ],
  "Daewoo": [
    "Alpheon",
    "Arcadia",
    "Chairman",
    "Cielo",
    "Damas",
    "Espero",
    "Evanda",
    "G2X",
    "Gentra",
    "Kalos",
    "Korando",
    "Lacetti",
    "Lanos",
    "Leganza",
    "Magnus",
    "Matiz",
    "Musso",
    "Nexia",
    "Nubira",
    "Prince",
    "Racer",
    "Rezzo",
    "Tacuma",
    "Tico",
    "Tosca",
    "Winstorm"
  ],
  "Daihatsu": [
    "Altis",
    "Applause",
    "Atrai",
    "Be go",
    "Boon",
    "Cast",
    "Ceria",
    "Charade",
    "Charmant",
    "Copen",
    "Cuore",
    "Delta",
    "Esse",
    "Feroza",
    "Gran Move",
    "Hijet",
    "Leeza",
    "Materia",
    "MAX",
    "Midget",
    "Mira",
    "Mira Gino",
    "Move",
    "Move Canbus",
    "Move Conte",
    "Move Latte",
    "Naked",
    "Opti",
    "Pyzar",
    "Rocky",
    "Sirion",
    "Sonica",
    "Storia",
    "Taft",
    "Tanto",
    "Tanto Exe",
    "Terios",
    "Terios Kid",
    "Trevis",
    "Wake",
    "Xenia",
    "YRV"
  ],
  "Datsun": [
    "240Z",
    "260Z",
    "280Z",
    "280ZX",
    "510",
    "620",
    "810",
    "Cherry",
    "GO",
    "GO+",
    "mi-DO",
    "on-DO",
    "redi-GO",
    "Sunny",
    "Violet"
  ],
  "DFSK": [
    "330",
    "370",
    "500",
    "580",
    "600",
    "C31",
    "C32",
    "C35",
    "C37",
    "Fengon 500",
    "Fengon 580",
    "Fengon E3",
    "Fengon ix5",
    "Fengon ix7",
    "Fengon S560",
    "Glory 330",
    "Glory 370",
    "Glory 500",
    "Glory 580",
    "K01",
    "K01H",
    "K05",
    "K07"
  ],
  "Dodge": [
    "400",
    "600",
    "Aries",
    "Avenger",
    "Caliber",
    "Caravan",
    "Challenger",
    "Charger",
    "Colt",
    "Coronet",
    "Dart",
    "Daytona",
    "Diplomat",
    "Durango",
    "Dynasty",
    "Grand Caravan",
    "Hornet",
    "Intrepid",
    "Journey",
    "Lancer",
    "Magnum",
    "Mirada",
    "Monaco",
    "Neon",
    "Nitro",
    "Omni",
    "Polara",
    "Raider",
    "RAM",
    "Ram Van",
    "Ram Wagon",
    "Ramcharger",
    "Rampage",
    "Shadow",
    "Spirit",
    "Stealth",
    "Stratus",
    "Viper",
    "WC series"
  ],
  "Dongfeng": [
    "370",
    "580",
    "A30",
    "A60",
    "AX3",
    "AX4",
    "AX5",
    "AX7",
    "AX9",
    "E11K",
    "E70",
    "EX1",
    "Fengguang 330",
    "Fengguang 370",
    "Fengguang 500",
    "Fengguang 580",
    "Fengguang S560",
    "Fengon 500",
    "Fengon 580",
    "Fengon E3",
    "Fengon ix5",
    "Fengon ix7",
    "Fengshen A60",
    "Fengshen AX7",
    "Fengshen E70",
    "Fengshen L60",
    "Joyear",
    "Joyear S50",
    "Joyear X3",
    "Joyear X5",
    "Joyear X6",
    "Nammi 01",
    "Rich",
    "S30",
    "T5"
  ],
  "DS Automobiles": [
    "3",
    "3 Crossback",
    "4",
    "4S",
    "5",
    "5LS",
    "6",
    "7",
    "7 Crossback",
    "8",
    "9",
    "N°8"
  ],
  "Exeed": [
    "LX",
    "RX",
    "TX",
    "TXL",
    "VX",
    "Yaoguang"
  ],
  "FAW": [
    "Besturn B30",
    "Besturn B50",
    "Besturn B70",
    "Besturn B90",
    "Besturn T33",
    "Besturn T77",
    "Besturn T99",
    "Besturn X40",
    "Besturn X80",
    "Hongqi E-HS3",
    "Hongqi E-HS9",
    "Hongqi H5",
    "Hongqi H7",
    "Hongqi H9",
    "Hongqi HS5",
    "Hongqi HS7",
    "Jinn",
    "Oley",
    "Vita",
    "Xiali"
  ],
  "Ferrari": [
    "208",
    "246",
    "250",
    "275",
    "288 GTO",
    "308",
    "328",
    "330",
    "348",
    "360",
    "365",
    "400",
    "412",
    "456",
    "458",
    "488",
    "512",
    "550",
    "575M",
    "599",
    "612",
    "812",
    "California",
    "Daytona SP3",
    "Dino",
    "Enzo",
    "F12",
    "F40",
    "F50",
    "F8",
    "FF",
    "GTC4Lusso",
    "LaFerrari",
    "Mondial",
    "Monza SP",
    "Portofino",
    "Purosangue",
    "Roma",
    "SF90 Stradale",
    "Testarossa"
  ],
  "Fiat": [
    "124",
    "124 Spider",
    "126",
    "127",
    "128",
    "130",
    "131",
    "132",
    "500",
    "500L",
    "500X",
    "600",
    "850",
    "Albea",
    "Argenta",
    "Barchetta",
    "Brava",
    "Bravo",
    "Cinquecento",
    "Coupe",
    "Croma",
    "Dino",
    "Doblo",
    "Ducato",
    "Duna",
    "Fiorino",
    "Freemont",
    "Fullback",
    "Grande Punto",
    "Idea",
    "Linea",
    "Marengo",
    "Marea",
    "Multipla",
    "Nuova 500",
    "Palio",
    "Panda",
    "Punto",
    "Qubo",
    "Regata",
    "Ritmo",
    "Scudo",
    "Sedici",
    "Seicento",
    "Siena",
    "Stilo",
    "Strada",
    "Talento",
    "Tempra",
    "Tipo",
    "Toro",
    "Ulysse",
    "Uno",
    "X1/9"
  ],
  "Ford": [
    "Aerostar",
    "Aspire",
    "B-Max",
    "Bronco",
    "Bronco Sport",
    "C-Max",
    "Capri",
    "Contour",
    "Corcel",
    "Cougar",
    "Courier",
    "Crown Victoria",
    "E-Series",
    "EcoSport",
    "Edge",
    "Equator",
    "Escape",
    "Escort",
    "Excursion",
    "Expedition",
    "Explorer",
    "F-150",
    "F-250",
    "F-350",
    "F-450",
    "Fairlane",
    "Falcon",
    "Fiesta",
    "Figo",
    "Five Hundred",
    "Flex",
    "Focus",
    "Freestar",
    "Freestyle",
    "Fusion",
    "Galaxy",
    "GT",
    "Ka",
    "Kuga",
    "Laser",
    "LTD",
    "Maverick",
    "Mondeo",
    "Mustang",
    "Mustang Mach-E",
    "Orion",
    "Pampa",
    "Probe",
    "Puma",
    "Ranger",
    "Ranger Raptor",
    "S-Max",
    "Scorpio",
    "Sierra",
    "Spectron",
    "Taunus",
    "Taurus",
    "Telstar",
    "Tempo",
    "Territory",
    "Thunderbird",
    "Torino",
    "Tourneo Connect",
    "Tourneo Courier",
    "Tourneo Custom",
    "Transit",
    "Transit Connect",
    "Transit Courier",
    "Transit Custom",
    "Verona",
    "Windstar",
    "Zephyr"
  ],
  "GAC": [
    "Aion LX",
    "Aion S",
    "Aion V",
    "Aion Y",
    "Empow",
    "GA3",
    "GA4",
    "GA5",
    "GA6",
    "GA8",
    "GE3",
    "GN6",
    "GN8",
    "GS3",
    "GS4",
    "GS5",
    "GS7",
    "GS8",
    "Trumpchi"
  ],
  "Geely": [
    "Atlas",
    "Atlas Pro",
    "Binrui",
    "Binrui Cool",
    "Boyue",
    "Boyue L",
    "Coolray",
    "Emgrand",
    "Emgrand 7",
    "Emgrand EC7",
    "Emgrand EC8",
    "Emgrand GT",
    "Emgrand GX7",
    "Emgrand X7",
    "GX2",
    "Haoyue",
    "Icon",
    "Jiaji",
    "LC",
    "LC Cross",
    "MK",
    "MK Cross",
    "Monjaro",
    "Otaka",
    "Preface",
    "SC7",
    "Tugella",
    "Xingyue",
    "Xingyue L",
    "Yuanjing X1",
    "Yuanjing X3",
    "Yuanjing X6"
  ],
  "Genesis": [
    "G70",
    "G80",
    "G80 Sport",
    "G90",
    "GV60",
    "GV70",
    "GV80",
    "GV80 Coupe"
  ],
  "GMC": [
    "Acadia",
    "Canyon",
    "Envoy",
    "Hummer EV",
    "Jimmy",
    "Safari",
    "Savana",
    "Sierra",
    "Sonoma",
    "Suburban",
    "Syclone",
    "Terrain",
    "Typhoon",
    "Vandura",
    "Yukon",
    "Yukon XL"
  ],
  "Great Wall": [
    "Deer",
    "Florid",
    "Hover",
    "Hover H3",
    "Hover H5",
    "Hover H6",
    "Hover M1",
    "Hover M2",
    "Hover M4",
    "Pegasus",
    "Peri",
    "Safe",
    "Sailor",
    "Sing",
    "Socool",
    "Voleex C10",
    "Voleex C30",
    "Wingle",
    "Wingle 5",
    "Wingle 6",
    "Wingle 7"
  ],
  "Haval": [
    "Chitu",
    "Cool Dog",
    "Dargo",
    "F5",
    "F7",
    "F7x",
    "H2",
    "H2s",
    "H3",
    "H4",
    "H5",
    "H6",
    "H6 Coupe",
    "H6S",
    "H7",
    "H8",
    "H9",
    "Jolion",
    "M6",
    "Raptor",
    "Shenshou",
    "Xiaolong",
    "Xiaolong Max"
  ],
  "Honda": [
    "Accord",
    "Acty",
    "Airwave",
    "Ascot",
    "Avancier",
    "Ballade",
    "Beat",
    "Brio",
    "Capa",
    "City",
    "Civic",
    "Civic Type R",
    "Clarity",
    "Concerto",
    "CR-V",
    "CR-Z",
    "Crossroad",
    "Domani",
    "E",
    "Edix",
    "Element",
    "Elite",
    "Elysion",
    "Fit",
    "Fit Aria",
    "Freed",
    "FR-V",
    "Grace",
    "Horizon",
    "HR-V",
    "Insight",
    "Inspire",
    "Integra",
    "Integra SJ",
    "Jade",
    "Jazz",
    "Lagreat",
    "Legend",
    "Life",
    "Logo",
    "MDX",
    "Mobilio",
    "N-Box",
    "N-One",
    "N-Wgn",
    "NSX",
    "Odyssey",
    "Orthia",
    "Partner",
    "Passport",
    "Pilot",
    "Prelude",
    "Quint",
    "Rafaga",
    "Ridgeline",
    "S-MX",
    "S2000",
    "S660",
    "Saber",
    "Shuttle",
    "Spirit",
    "Stepwgn",
    "Stream",
    "That's",
    "Today",
    "Torneo",
    "Vamos",
    "Vezel",
    "Vigor",
    "Z",
    "Zest"
  ],
  "Hummer": [
    "H1",
    "H2",
    "H3",
    "H3T",
    "EV",
    "EV SUV"
  ],
  "Hyundai": [
    "Accent",
    "Atos",
    "Avante",
    "Azera",
    "Bayon",
    "Casper",
    "Celesta",
    "Centennial",
    "Click",
    "Creta",
    "Elantra",
    "Eon",
    "Equus",
    "Excel",
    "Galloper",
    "Genesis",
    "Genesis Coupe",
    "Getz",
    "Grace",
    "Grand Santa Fe",
    "Grand Starex",
    "Grandeur",
    "H-1",
    "H200",
    "HB20",
    "i10",
    "i20",
    "i30",
    "i40",
    "Ioniq",
    "Ioniq 5",
    "Ioniq 6",
    "Ioniq 7",
    "ix20",
    "ix35",
    "ix55",
    "Kona",
    "Lavita",
    "Mighty",
    "Mistra",
    "Matrix",
    "Maxcruz",
    "Nexo",
    "Palisade",
    "Pony",
    "Porter",
    "Reina",
    "Santa Cruz",
    "Santa Fe",
    "Santro",
    "Solaris",
    "Sonata",
    "Starex",
    "Staria",
    "Stellar",
    "Terracan",
    "Tiburon",
    "Trajet",
    "Tucson",
    "Tuscani",
    "Veloster",
    "Veracruz",
    "Verna",
    "Xcent",
    "XG"
  ],
  "Infiniti": [
    "EX",
    "FX",
    "G",
    "I",
    "J",
    "JX",
    "M",
    "Q30",
    "Q40",
    "Q45",
    "Q50",
    "Q60",
    "Q70",
    "QX30",
    "QX4",
    "QX50",
    "QX55",
    "QX56",
    "QX60",
    "QX70",
    "QX80"
  ],
  "Isuzu": [
    "Amigo",
    "Ascender",
    "Axiom",
    "Bighorn",
    "Campo",
    "D-Max",
    "Elf",
    "Fargo",
    "Faster",
    "Forward",
    "Giga",
    "Hombre",
    "i-280",
    "i-290",
    "i-350",
    "i-370",
    "KB",
    "MU",
    "MU-7",
    "MU-X",
    "N-Series",
    "Oasis",
    "Panther",
    "Rodeo",
    "TF",
    "Trooper",
    "VehiCROSS",
    "Wizard"
  ],
  "JAC": [
    "iEVA50",
    "iEVS4",
    "J2",
    "J3",
    "J4",
    "J5",
    "J6",
    "J7",
    "J8",
    "M1",
    "M2",
    "M3",
    "M4",
    "M5",
    "M6",
    "Refine M3",
    "Refine M4",
    "Refine M5",
    "Refine R3",
    "Refine S2",
    "Refine S3",
    "Refine S4",
    "Refine S5",
    "Refine S7",
    "T6",
    "T8",
    "X200"
  ],
  "Jaecoo": [
    "J7",
    "J8",
    "J6",
    "J5"
  ],
  "Jaguar": [
    "E-Pace",
    "F-Pace",
    "F-Type",
    "I-Pace",
    "S-Type",
    "X-Type",
    "XE",
    "XF",
    "XJ",
    "XJ12",
    "XJ6",
    "XJ8",
    "XJR",
    "XJS",
    "XK",
    "XK8",
    "XKR"
  ],
  "Jeep": [
    "Avenger",
    "Cherokee",
    "CJ",
    "Commander",
    "Compass",
    "Gladiator",
    "Grand Cherokee",
    "Grand Wagoneer",
    "Liberty",
    "Patriot",
    "Renegade",
    "Wagoneer",
    "Wrangler",
    "Wrangler Unlimited"
  ],
  "Jetour": [
    "Dashing",
    "X70",
    "X70 Coupe",
    "X70 Plus",
    "X90",
    "X90 Plus",
    "X95",
    "Traveller"
  ],
  "Kia": [
    "Avella",
    "Bongo",
    "Cadenza",
    "Capital",
    "Carens",
    "Carnival",
    "Carstar",
    "Ceed",
    "Cerato",
    "Clarus",
    "Concord",
    "Elan",
    "Enterprise",
    "EV6",
    "EV9",
    "Forte",
    "Forte K3",
    "Granbird",
    "Joice",
    "K3",
    "K5",
    "K7",
    "K8",
    "K9",
    "Magentis",
    "Mohave",
    "Morning",
    "Niro",
    "Opirus",
    "Optima",
    "Pegas",
    "Picanto",
    "Pregio",
    "Pride",
    "ProCeed",
    "Quoris",
    "Ray",
    "Retona",
    "Rio",
    "Rio X-Line",
    "Seltos",
    "Sepia",
    "Shuma",
    "Sorento",
    "Soul",
    "Spectra",
    "Sportage",
    "Stinger",
    "Stonic",
    "Telluride",
    "Towner",
    "Trace",
    "Venga",
    "XCeed"
  ],
  "Koenigsegg": [
    "Agera",
    "CC8S",
    "CCR",
    "CCX",
    "Gemera",
    "Jesko",
    "One:1",
    "Regera"
  ],
  "Lada": [
    "110",
    "111",
    "112",
    "2101",
    "2102",
    "2103",
    "2104",
    "2105",
    "2106",
    "2107",
    "2108",
    "2109",
    "21099",
    "2110",
    "2111",
    "2112",
    "2113",
    "2114",
    "2115",
    "2120",
    "2121",
    "2131",
    "2329",
    "4x4",
    "Aura",
    "Granta",
    "Granta Cross",
    "Granta Drive Active",
    "Granta Sport",
    "Iskra",
    "Kalina",
    "Kalina Cross",
    "Kalina Sport",
    "Largus",
    "Largus Cross",
    "Niva",
    "Niva Legend",
    "Niva Travel",
    "Oka",
    "Priora",
    "Rapan",
    "Revolution",
    "Samara",
    "Tarzan",
    "Vesta",
    "Vesta Cross",
    "Vesta Sport",
    "Vesta SW",
    "Vesta SW Cross",
    "XRAY",
    "XRAY Cross",
    "Zhiguli"
  ],
  "Lamborghini": [
    "350GT",
    "400GT",
    "Aventador",
    "Centenario",
    "Countach",
    "Diablo",
    "Espada",
    "Gallardo",
    "Huracán",
    "Islero",
    "Jalpa",
    "Jarama",
    "LM002",
    "Miura",
    "Murciélago",
    "Reventón",
    "Sesto Elemento",
    "Silhouette",
    "Urraco",
    "Urus",
    "Veneno"
  ],
  "Lancia": [
    "2000",
    "Beta",
    "Dedra",
    "Delta",
    "Flaminia",
    "Flavia",
    "Fulvia",
    "Gamma",
    "Hyena",
    "K",
    "Kappa",
    "Lybra",
    "Montecarlo",
    "Musa",
    "Phedra",
    "Prisma",
    "Stratos",
    "Thema",
    "Thesis",
    "Trevi",
    "Voyager",
    "Y",
    "Y10",
    "Ypsilon",
    "Zeta"
  ],
  "Land Rover": [
    "Defender",
    "Defender 90",
    "Defender 110",
    "Defender 130",
    "Discovery",
    "Discovery Sport",
    "Freelander",
    "Range Rover",
    "Range Rover Evoque",
    "Range Rover Sport",
    "Range Rover Velar",
    "Series I",
    "Series II",
    "Series III"
  ],
  "Lexus": [
    "CT",
    "ES",
    "GS",
    "GS F",
    "GX",
    "HS",
    "IS",
    "IS F",
    "LC",
    "LFA",
    "LM",
    "LS",
    "LX",
    "NX",
    "RC",
    "RC F",
    "RX",
    "RZ",
    "SC",
    "UX",
    "UX 300e"
  ],
  "Li Auto": [
    "L6",
    "L7",
    "L8",
    "L9",
    "Mega",
    "One"
  ],
  "Lifan": [
    "320",
    "330",
    "520",
    "530",
    "620",
    "630",
    "650",
    "720",
    "820",
    "Breez",
    "Cebrium",
    "Celliya",
    "Foison",
    "Murman",
    "Myway",
    "Smily",
    "Solano",
    "X50",
    "X60",
    "X70",
    "X80"
  ],
  "Lincoln": [
    "Aviator",
    "Blackwood",
    "Continental",
    "Corsair",
    "LS",
    "Mark",
    "Mark LT",
    "MKC",
    "MKS",
    "MKT",
    "MKX",
    "MKZ",
    "Nautilus",
    "Navigator",
    "Town Car",
    "Zephyr"
  ],
  "Lotus": [
    "Eletre",
    "Elise",
    "Emira",
    "Esprit",
    "Evija",
    "Evora",
    "Exige",
    "Seven"
  ],
  "Lucid": [
    "Air",
    "Gravity"
  ],
  "Maserati": [
    "3200 GT",
    "Ghibli",
    "GranCabrio",
    "GranSport",
    "GranTurismo",
    "Grecale",
    "Levante",
    "MC12",
    "MC20",
    "Quattroporte",
    "Spyder"
  ],
  "Maybach": [
    "57",
    "62",
    "GLS",
    "S-Class",
    "S580",
    "S680"
  ],
  "Mazda": [
    "2",
    "3",
    "5",
    "6",
    "121",
    "323",
    "626",
    "929",
    "Atenza",
    "Axela",
    "AZ-1",
    "AZ-Offroad",
    "AZ-Wagon",
    "B-Series",
    "Biante",
    "BT-50",
    "CX-3",
    "CX-30",
    "CX-5",
    "CX-50",
    "CX-60",
    "CX-7",
    "CX-70",
    "CX-8",
    "CX-80",
    "CX-9",
    "CX-90",
    "Carol",
    "Demio",
    "Eunos",
    "Familia",
    "Flair",
    "Laputa",
    "Luce",
    "Millenia",
    "MPV",
    "MX-3",
    "MX-30",
    "MX-5",
    "MX-6",
    "Navajo",
    "Persona",
    "Premacy",
    "Proceed",
    "RX-7",
    "RX-8",
    "Scrum",
    "Sentia",
    "Spiano",
    "Tribute",
    "Verisa",
    "Xedos"
  ],
  "McLaren": [
    "540C",
    "570S",
    "600LT",
    "650S",
    "675LT",
    "720S",
    "765LT",
    "Artura",
    "F1",
    "GT",
    "MP4-12C",
    "P1",
    "Sabre",
    "Senna",
    "Speedtail"
  ],
  "Mercedes-Benz": [
    "A-Class",
    "B-Class",
    "C-Class",
    "CL-Class",
    "CLA",
    "CLK",
    "CLS",
    "E-Class",
    "EQA",
    "EQB",
    "EQC",
    "EQE",
    "EQS",
    "EQV",
    "G-Class",
    "GL-Class",
    "GLA",
    "GLB",
    "GLC",
    "GLE",
    "GLK",
    "GLS",
    "M-Class",
    "R-Class",
    "S-Class",
    "SL-Class",
    "SLC",
    "SLK",
    "SLR McLaren",
    "SLS AMG",
    "T-Class",
    "V-Class",
    "Vaneo",
    "Viano",
    "Vito",
    "X-Class",
    "190",
    "300",
    "600",
    "AMG GT",
    "AMG GT 4-Door",
    "Maybach S-Class",
    "Maybach GLS"
  ],
  "MG": [
    "3",
    "5",
    "6",
    "7",
    "350",
    "550",
    "750",
    "Cyberster",
    "E-Motion",
    "F",
    "GS",
    "GT",
    "Hector",
    "HS",
    "Marvel R",
    "MG4",
    "MG5",
    "MG6",
    "One",
    "RX5",
    "S5",
    "TF",
    "ZS",
    "ZT",
    "ZT-T"
  ],
  "Mini": [
    "Aceman",
    "Clubman",
    "Cooper",
    "Cooper S",
    "Countryman",
    "Coupe",
    "Hatch",
    "John Cooper Works",
    "Paceman",
    "Roadster"
  ],
  "Mitsubishi": [
    "3000GT",
    "Airtrek",
    "ASX",
    "Attrage",
    "Carisma",
    "Challenger",
    "Chariot",
    "Colt",
    "Cordia",
    "Delica",
    "Diamante",
    "Dignity",
    "Dion",
    "Eclipse",
    "Eclipse Cross",
    "eK",
    "Emeraude",
    "Endeavor",
    "Eterna",
    "Freeca",
    "FTO",
    "Galant",
    "Galant Fortis",
    "Grandis",
    "GTO",
    "i",
    "i-MiEV",
    "Jeep",
    "L200",
    "L300",
    "L400",
    "Lancer",
    "Lancer Cedia",
    "Lancer Evolution",
    "Lancer Ralliart",
    "Legnum",
    "Libero",
    "Maven",
    "Minica",
    "Minicab",
    "Mirage",
    "Montero",
    "Montero Sport",
    "Outlander",
    "Pajero",
    "Pajero iO",
    "Pajero Junior",
    "Pajero Mini",
    "Pajero Pinin",
    "Pajero Sport",
    "Raider",
    "RVR",
    "Shogun",
    "Shogun Pinin",
    "Shogun Sport",
    "Sigma",
    "Space Gear",
    "Space Runner",
    "Space Star",
    "Space Wagon",
    "Starion",
    "Strada",
    "Tredia",
    "Triton",
    "Xforce",
    "Xpander"
  ],
  "Moskvich": [
    "3",
    "3e",
    "4",
    "6",
    "8",
    "2140",
    "2141",
    "2335",
    "400",
    "401",
    "402",
    "403",
    "407",
    "408",
    "412",
    "2136",
    "2137",
    "2138",
    "2142",
    "2901",
    "Aleko",
    "Duet",
    "Ivan Kalita",
    "KnAZ",
    "Svjatogor",
    "Yuri Dolgorukiy"
  ],
  "NIO": [
    "EC6",
    "EC7",
    "ES6",
    "ES7",
    "ES8",
    "ET5",
    "ET7",
    "ET9"
  ],
  "Nissan": [
    "100NX",
    "200SX",
    "240SX",
    "280ZX",
    "300ZX",
    "350Z",
    "370Z",
    "AD",
    "Almera",
    "Almera Classic",
    "Almera Tino",
    "Altima",
    "Armada",
    "Ariya",
    "Atlas",
    "Auster",
    "Avenir",
    "Bassara",
    "BE-1",
    "Bluebird",
    "Bluebird Sylphy",
    "Cabstar",
    "Caravan",
    "Cefiro",
    "Cherry",
    "Cima",
    "Civillian",
    "Clipper",
    "Crew",
    "Cube",
    "Datsun",
    "Dayz",
    "Dualis",
    "Elgrand",
    "Exa",
    "Expert",
    "Fairlady Z",
    "Figaro",
    "Frontier",
    "Fuga",
    "Gazelle",
    "Gloria",
    "GT-R",
    "Homy",
    "Hypermini",
    "Interstar",
    "Juke",
    "King Cab",
    "Kix",
    "Kubistar",
    "Largo",
    "Lafesta",
    "Langley",
    "Lannia",
    "Laurel",
    "Laurel",
    "Leaf",
    "Leopard",
    "Liberty",
    "Livina",
    "Lucino",
    "March",
    "Maxima",
    "Micra",
    "Mistral",
    "Moco",
    "Murano",
    "Navara",
    "Note",
    "NP300",
    "NV200",
    "NV300",
    "NV350",
    "NX Coupe",
    "Otti",
    "Pao",
    "Pathfinder",
    "Patrol",
    "PickUp",
    "Pino",
    "Pixo",
    "Platina",
    "Prairie",
    "Presage",
    "Presea",
    "Primastar",
    "Primera",
    "Pulsar",
    "Qashqai",
    "Qashqai+2",
    "Quest",
    "R'nessa",
    "Rasheen",
    "Rocky",
    "Rogue",
    "Rogue Sport",
    "Safari",
    "S-Cargo",
    "Sentra",
    "Serena",
    "Silvia",
    "Skyline",
    "Skyline Crossover",
    "Skyline GT-R",
    "Stagea",
    "Stanza",
    "Sunny",
    "Sylphy",
    "Teana",
    "Terrano",
    "Terrano II",
    "Tiida",
    "Titan",
    "Trade",
    "Urvan",
    "Vanette",
    "Versa",
    "Wingroad",
    "X-Terra",
    "X-Trail",
    "Xterra",
    "Z"
  ],
  "Omoda": [
    "C5",
    "S5",
    "5",
    "7",
    "9"
  ],
  "Opel": [
    "Adam",
    "Agila",
    "Ampera",
    "Ampera-e",
    "Antara",
    "Arena",
    "Ascona",
    "Astra",
    "Calibra",
    "Campo",
    "Cascada",
    "Cavalier",
    "Combo",
    "Commodore",
    "Corsa",
    "Crossland",
    "Diplomat",
    "Frontera",
    "Grandland",
    "GT",
    "Insignia",
    "Kadett",
    "Karl",
    "Manta",
    "Meriva",
    "Mokka",
    "Monaro",
    "Monterey",
    "Movano",
    "Omega",
    "Pickup",
    "Rekord",
    "Senator",
    "Signum",
    "Sintra",
    "Speedster",
    "Tigra",
    "Vectra",
    "Vivaro",
    "Zafira"
  ],
  "Ora": [
    "Ballet Cat",
    "Funky Cat",
    "Good Cat",
    "Lightning Cat",
    "Punk Cat",
    "R1",
    "R2",
    "White Cat"
  ],
  "Pagani": [
    "Huayra",
    "Huayra BC",
    "Huayra Roadster",
    "Utopia",
    "Zonda",
    "Zonda F",
    "Zonda R",
    "Zonda Revolucion"
  ],
  "Peugeot": [
    "1007",
    "104",
    "106",
    "107",
    "108",
    "2008",
    "201",
    "202",
    "203",
    "204",
    "205",
    "206",
    "207",
    "208",
    "3008",
    "301",
    "304",
    "305",
    "306",
    "307",
    "308",
    "309",
    "4007",
    "4008",
    "403",
    "404",
    "405",
    "406",
    "407",
    "408",
    "5008",
    "504",
    "505",
    "508",
    "604",
    "605",
    "607",
    "806",
    "807",
    "Bipper",
    "Boxer",
    "Expert",
    "iOn",
    "J5",
    "J7",
    "J9",
    "Partner",
    "RCZ",
    "Rifter",
    "TePee",
    "Traveller"
  ],
  "Polestar": [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6"
  ],
  "Porsche": [
    "356",
    "718",
    "911",
    "912",
    "914",
    "918 Spyder",
    "924",
    "928",
    "944",
    "959",
    "968",
    "Boxster",
    "Carrera GT",
    "Cayenne",
    "Cayman",
    "Macan",
    "Panamera",
    "Taycan"
  ],
  "RAM": [
    "1500",
    "2500",
    "3500",
    "4000",
    "5500",
    "C/V",
    "ProMaster",
    "ProMaster City",
    "Rampage",
    "TRX"
  ],
  "Ravon": [
    "Gentra",
    "Matiz",
    "Nexia",
    "R2",
    "R3",
    "R4",
    "Spark"
  ],
  "Renault": [
    "10",
    "11",
    "12",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
    "21",
    "25",
    "30",
    "4",
    "5",
    "6",
    "8",
    "9",
    "Alaskan",
    "Arkana",
    "Austral",
    "Avantime",
    "Captur",
    "Caravelle",
    "Clio",
    "Clio V6",
    "Colorado",
    "Duster",
    "Duster Oroch",
    "Espace",
    "Express",
    "Fluence",
    "Fuego",
    "Grand Espace",
    "Grand Modus",
    "Grand Scenic",
    "Kangoo",
    "Kaptur",
    "Koleos",
    "Kwid",
    "Laguna",
    "Latitude",
    "Lodgy",
    "Logan",
    "Master",
    "Megane",
    "Megane E-Tech",
    "Modus",
    "Oroch",
    "Rodeo",
    "Safrane",
    "Sandero",
    "Sandero Stepway",
    "Scenic",
    "Scenic E-Tech",
    "Spider",
    "Symbol",
    "Talisman",
    "Trafic",
    "Triber",
    "Twingo",
    "Twizy",
    "Vel Satis",
    "Wind",
    "Zoe"
  ],
  "Rivian": [
    "R1T",
    "R1S",
    "R2",
    "R3"
  ],
  "Rolls-Royce": [
    "Camargue",
    "Corniche",
    "Cullinan",
    "Dawn",
    "Ghost",
    "Park Ward",
    "Phantom",
    "Phantom Coupe",
    "Phantom Drophead",
    "Silver Cloud",
    "Silver Dawn",
    "Silver Ghost",
    "Silver Shadow",
    "Silver Spirit",
    "Silver Spur",
    "Spectre",
    "Wraith"
  ],
  "Rover": [
    "100",
    "200",
    "25",
    "400",
    "45",
    "600",
    "75",
    "800",
    "CityRover",
    "Metro",
    "Mini",
    "Montego",
    "P3",
    "P4",
    "P5",
    "P6",
    "SD1",
    "Streetwise"
  ],
  "Saab": [
    "9-2X",
    "9-3",
    "9-4X",
    "9-5",
    "9-7X",
    "90",
    "900",
    "9000",
    "96",
    "99",
    "Sonett"
  ],
  "SEAT": [
    "Alhambra",
    "Altea",
    "Arosa",
    "Arona",
    "Ateca",
    "Córdoba",
    "Exeo",
    "Fura",
    "Ibiza",
    "Inca",
    "León",
    "Málaga",
    "Marbella",
    "Mii",
    "Panda",
    "Ronda",
    "Tarraco",
    "Terra",
    "Toledo"
  ],
  "Skoda": [
    "Citigo",
    "Elroq",
    "Enyaq",
    "Enyaq Coupe",
    "Fabia",
    "Favorit",
    "Felicia",
    "Forman",
    "Kamiq",
    "Karoq",
    "Kodiaq",
    "Kushaq",
    "Octavia",
    "Octavia Scout",
    "Octavia vRS",
    "Pickup",
    "Praktik",
    "Rapid",
    "Roomster",
    "Scala",
    "Slavia",
    "Superb",
    "Yeti",
    "100",
    "105",
    "120",
    "130",
    "135",
    "136"
  ],
  "Smart": [
    "Forfour",
    "Fortwo",
    "Fortwo Cabrio",
    "Fortwo Electric Drive",
    "Roadster",
    "#1",
    "#3"
  ],
  "Sollers": [
    "Argo",
    "Atlant",
    "ST6"
  ],
  "SsangYong": [
    "Actyon",
    "Chairman",
    "Family",
    "Istana",
    "Kalos",
    "Korando",
    "Korando Sports",
    "Korando Turismo",
    "Kyron",
    "Musso",
    "Musso Grand",
    "Rexton",
    "Rexton Sports",
    "Rodius",
    "Stavic",
    "Tivoli",
    "Tivoli Grand",
    "XLV"
  ],
  "Subaru": [
    "Ascent",
    "Baja",
    "BRZ",
    "Crosstrek",
    "Exiga",
    "Forester",
    "Impreza",
    "Justy",
    "Legacy",
    "Levorg",
    "Libero",
    "Outback",
    "Pleo",
    "R1",
    "R2",
    "Sambar",
    "Solterra",
    "Stella",
    "SVX",
    "Traviq",
    "Trezia",
    "Tribeca",
    "Vivio",
    "WRX",
    "WRX STI",
    "XV"
  ],
  "Suzuki": [
    "Aerio",
    "Alto",
    "Baleno",
    "Cappuccino",
    "Cara",
    "Carry",
    "Celerio",
    "Cervo",
    "Cultus",
    "Ertiga",
    "Escudo",
    "Every",
    "Fronte",
    "Grand Vitara",
    "Hustler",
    "Ignis",
    "Jimny",
    "Kizashi",
    "Liana",
    "MR Wagon",
    "Palette",
    "Samurai",
    "S-Cross",
    "SJ",
    "Solio",
    "Splash",
    "Swift",
    "SX4",
    "SX4 S-Cross",
    "Vitara",
    "Wagon R",
    "Wagon R+",
    "X-90",
    "XL6",
    "XL7"
  ],
  "Tank": [
    "300",
    "400",
    "500",
    "700",
    "800"
  ],
  "Tata": [
    "Altroz",
    "Aria",
    "Bolt",
    "Curvv",
    "Estate",
    "Harrier",
    "Hexa",
    "Indica",
    "Indigo",
    "Manza",
    "Nano",
    "Nexon",
    "Punch",
    "Safari",
    "Sierra",
    "Sumo",
    "Telcoline",
    "Tiago",
    "Tigor",
    "Venture",
    "Xenon",
    "Zest"
  ],
  "Tesla": [
    "Cybertruck",
    "Model 3",
    "Model S",
    "Model X",
    "Model Y",
    "Roadster",
    "Semi"
  ],
  "Toyota": [
    "4Runner",
    "Allex",
    "Allion",
    "Alphard",
    "Altezza",
    "Aqua",
    "Aurion",
    "Auris",
    "Avalon",
    "Avanza",
    "Avensis",
    "Aygo",
    "bB",
    "Belta",
    "Blizzard",
    "Brevis",
    "C-HR",
    "Caldina",
    "Cami",
    "Camry",
    "Camry Solara",
    "Carina",
    "Carina E",
    "Cavalier",
    "Celica",
    "Celsior",
    "Century",
    "Chaser",
    "Classic",
    "Coaster",
    "Comfort",
    "Corolla",
    "Corolla Cross",
    "Corolla Rumion",
    "Corolla Spacio",
    "Corolla Verso",
    "Corona",
    "Corsa",
    "Cressida",
    "Cresta",
    "Crown",
    "Crown Majesta",
    "Curren",
    "Cynos",
    "Duet",
    "Echo",
    "Esquire",
    "Estima",
    "FJ Cruiser",
    "Fortuner",
    "Funcargo",
    "GAZOO Racing",
    "GranAce",
    "Grand HiAce",
    "Granvia",
    "GT86",
    "Harrier",
    "HiAce",
    "Highlander",
    "Hilux",
    "Hilux Surf",
    "Innova",
    "Ipsum",
    "iQ",
    "Ist",
    "Kluger",
    "Land Cruiser",
    "Land Cruiser Prado",
    "LiteAce",
    "Mark II",
    "Mark X",
    "Mark X Zio",
    "MasterAce",
    "Matrix",
    "Mega Cruiser",
    "Mirai",
    "Model F",
    "MR2",
    "MR-S",
    "Noah",
    "Opa",
    "Origin",
    "Paseo",
    "Passo",
    "Picnic",
    "Platz",
    "Porte",
    "Premio",
    "Previa",
    "Prius",
    "Prius Alpha",
    "Prius C",
    "Prius Plus",
    "Prius v",
    "ProAce",
    "ProAce City",
    "ProAce Verso",
    "Probox",
    "Quantum",
    "Ractis",
    "Raize",
    "Raum",
    "RAV4",
    "RAV4 EV",
    "Regius",
    "Rush",
    "SAI",
    "Sequoia",
    "Sera",
    "Sienna",
    "Sienta",
    "Soarer",
    "Solara",
    "Space Cruiser",
    "Sparky",
    "Sports 800",
    "SportsVan",
    "Starlet",
    "Succeed",
    "Supra",
    "T100",
    "Tundra",
    "Urban Cruiser",
    "Vellfire",
    "Venza",
    "Verossa",
    "Verso",
    "Verso-S",
    "Vios",
    "Vitz",
    "Voltz",
    "Voxy",
    "WiLL",
    "WiLL Cypha",
    "Windom",
    "Wish",
    "Yaris",
    "Yaris Cross",
    "Yaris Verso"
  ],
  "UAZ": [
    "3151",
    "31512",
    "31514",
    "31519",
    "3153",
    "3160",
    "3162",
    "3741",
    "3909",
    "3962",
    "452",
    "469",
    "Bukhanka",
    "Cargo",
    "Hunter",
    "Patriot",
    "Pickup",
    "Profi",
    "SGR",
    "Simbir"
  ],
  "Volkswagen": [
    "Amarok",
    "Apollo",
    "Arteon",
    "Atlas",
    "Atlas Cross Sport",
    "Beetle",
    "Bora",
    "Caddy",
    "California",
    "Caravelle",
    "CC",
    "Clasico",
    "Corrado",
    "Crafter",
    "CrossFox",
    "CrossGolf",
    "CrossPolo",
    "CrossTouran",
    "Derby",
    "Eos",
    "EuroVan",
    "Fox",
    "Fusca",
    "Gol",
    "Golf",
    "Golf Country",
    "Golf Plus",
    "Golf R",
    "Golf Sportsvan",
    "ID.3",
    "ID.4",
    "ID.5",
    "ID.6",
    "ID.7",
    "ID.Buzz",
    "Jetta",
    "K70",
    "Käfer",
    "Kombi",
    "Lamando",
    "Lavida",
    "Lupo",
    "Magotan",
    "Master",
    "Multivan",
    "New Beetle",
    "Parati",
    "Passat",
    "Passat CC",
    "Phaeton",
    "Pointer",
    "Polo",
    "Quantum",
    "Routan",
    "Santana",
    "Saveiro",
    "Scirocco",
    "Sharan",
    "SpaceFox",
    "SpaceCross",
    "SP2",
    "Suran",
    "T-Cross",
    "T-Roc",
    "Taigo",
    "Talagon",
    "Taos",
    "Tarok",
    "Tayron",
    "Teramont",
    "Tiguan",
    "Tiguan Allspace",
    "Touareg",
    "Touran",
    "Transporter",
    "Type 2",
    "Type 3",
    "Type 4",
    "Up!",
    "Vanagon",
    "Vento",
    "Viloran",
    "Virtus",
    "Voyage"
  ],
  "Volvo": [
    "240",
    "340",
    "360",
    "440",
    "460",
    "480",
    "740",
    "760",
    "780",
    "850",
    "940",
    "960",
    "C30",
    "C40",
    "C70",
    "EX30",
    "EX90",
    "P1800",
    "S40",
    "S60",
    "S70",
    "S80",
    "S90",
    "V40",
    "V50",
    "V60",
    "V70",
    "V90",
    "XC40",
    "XC60",
    "XC70",
    "XC90"
  ],
  "Voyah": [
    "Chasing Light",
    "Dream",
    "Free",
    "Passion",
    "Zhuiguang"
  ],
  "Wuling": [
    "Air EV",
    "Almaz",
    "Binguo",
    "Capa",
    "Confero",
    "Cortez",
    "Formo",
    "Hongguang",
    "Hongguang Mini EV",
    "Hongguang Plus",
    "Hongguang S",
    "Hongguang V",
    "Journey",
    "Rongguang",
    "Sunshine",
    "Victory",
    "Xingchi",
    "Zhengtu"
  ],
  "Xiaomi": [
    "SU7",
    "SU7 Max",
    "SU7 Pro"
  ],
  "XPeng": [
    "G3",
    "G6",
    "G9",
    "P5",
    "P7",
    "X9"
  ],
  "Zeekr": [
    "001",
    "009",
    "X",
    "Mix",
    "007"
  ],
  "Zotye": [
    "2008",
    "5008",
    "E200",
    "SR7",
    "SR9",
    "T200",
    "T300",
    "T500",
    "T600",
    "T700",
    "Z100",
    "Z200",
    "Z300",
    "Z500",
    "Z700"
  ]
};
// Функция заполнения годов
function populateYears() {
    const yearSelect = document.getElementById('year');
    const currentYear = new Date().getFullYear();
    for (let y = currentYear + 1; y >= 1970; y--) {
        const option = document.createElement('option');
        option.value = y;
        option.textContent = y;
        yearSelect.appendChild(option);
    }
}

// Обработка выбора марки (переключение на ручной ввод)
function handleBrandChange() {
    const brandSelect = document.getElementById('brand');
    const brandOther = document.getElementById('brand_other');
    if (brandSelect.value === 'other') {
        brandSelect.style.display = 'none';
        brandOther.style.display = 'block';
        brandOther.required = true;
        brandSelect.required = false;
    } else {
        brandSelect.style.display = 'block';
        brandOther.style.display = 'none';
        brandOther.required = false;
        brandSelect.required = true;
    }
    updateModels();
}

// Обновление списка моделей в зависимости от выбранной марки
function updateModels() {
    const brandSelect = document.getElementById('brand');
    const brandOther = document.getElementById('brand_other');
    const modelSelect = document.getElementById('model');
    const modelOther = document.getElementById('model_other');

    // Определяем выбранную марку
    let selectedBrand;
    if (brandSelect.style.display !== 'none' && brandSelect.value !== 'other') {
        selectedBrand = brandSelect.value;
    } else if (brandOther.style.display !== 'none') {
        selectedBrand = brandOther.value.trim();
    } else {
        selectedBrand = null;
    }

    // Очищаем список моделей
    modelSelect.innerHTML = '<option value="">-- Выберите модель --</option>';
    modelOther.style.display = 'none';
    modelOther.required = false;
    modelSelect.style.display = 'block';
    modelSelect.required = true;

    if (selectedBrand && selectedBrand !== '' && modelsByBrand[selectedBrand]) {
        // Если марка есть в справочнике, добавляем её модели
        modelsByBrand[selectedBrand].forEach(model => {
            const option = document.createElement('option');
            option.value = model;
            option.textContent = model;
            modelSelect.appendChild(option);
        });
        // Добавляем пункт "Другая модель"
        const otherOption = document.createElement('option');
        otherOption.value = 'other_model';
        otherOption.textContent = 'Другая модель (вписать вручную)';
        modelSelect.appendChild(otherOption);
    } else {
        // Если марка не в справочнике или введена вручную, показываем только "Другую модель"
        const otherOption = document.createElement('option');
        otherOption.value = 'other_model';
        otherOption.textContent = 'Другая модель (вписать вручную)';
        modelSelect.appendChild(otherOption);
    }
}

// Обработка выбора модели (переключение на ручной ввод)
function handleModelChange() {
    const modelSelect = document.getElementById('model');
    const modelOther = document.getElementById('model_other');
    if (modelSelect.value === 'other_model') {
        modelSelect.style.display = 'none';
        modelOther.style.display = 'block';
        modelOther.required = true;
        modelSelect.required = false;
    } else {
        modelSelect.style.display = 'block';
        modelOther.style.display = 'none';
        modelOther.required = false;
        modelSelect.required = true;
    }
}

// ... остальной код (списки марок, функции populateYears и т.д.) ...

// Отправка формы
function handleSubmit(event) {
    event.preventDefault();
    console.log('Submit triggered');  // Лог

    let brandValue = document.getElementById('brand').value;
    if (document.getElementById('brand_other').style.display !== 'none') {
        brandValue = document.getElementById('brand_other').value.trim();
        if (!brandValue) {
            alert('Введите марку');
            return;
        }
    }

    let modelValue = document.getElementById('model').value;
    if (document.getElementById('model_other').style.display !== 'none') {
        modelValue = document.getElementById('model_other').value.trim();
        if (!modelValue) {
            alert('Введите модель');
            return;
        }
    }

    const formData = {
        brand: brandValue,
        model: modelValue,
        year: document.getElementById('year').value,
        fuel: document.getElementById('fuel').value,
        engine_volume: document.getElementById('engine_volume').value,
        mileage: document.getElementById('mileage').value,
        nickname: document.getElementById('nickname').value
    };

    if (!formData.year || !formData.fuel || !formData.mileage) {
        alert('Пожалуйста, заполните все обязательные поля');
        return;
    }

    console.log('Form data:', formData);  // Лог

    if (window.Telegram && Telegram.WebApp) {
        Telegram.WebApp.sendData(JSON.stringify(formData));
        console.log('Data sent');  // Лог
    } else {
        alert('Форма должна открываться через Telegram');
    }
}

// Инициализация
window.addEventListener('DOMContentLoaded', () => {
    console.log('DOM loaded');
    if (window.Telegram && Telegram.WebApp) {
        console.log('Telegram WebApp found');
        Telegram.WebApp.ready();
        Telegram.WebApp.MainButton.setText('Отправить').show().onClick(() => {
            console.log('Main button clicked');
            document.getElementById('carForm').dispatchEvent(new Event('submit'));
        });
    } else {
        console.log('Telegram WebApp not present');
    }
});

// Привязка обработчика к форме (добавить, если отсутствует)
document.getElementById('carForm').addEventListener('submit', handleSubmit);
